### ISSUE TITLE
Flush logfile on interrupt

### ISSUE THREAD

**Issue by shak-mar** [froozen/pybot#5]
When you kill pybot via Control-C, the logfile is not written correctly. You should probably catch the `KeyboardInterrupt` exception top-level and flush the logfile.

**Comment by froozen** [comment]
I'm pretty sure that [the way the log is handled right now][log.py] makes sure that nothing is lost, even if pybot is closed via `^C` or killed. Please correct me if I'm wrong with this.

[log.py]: https://github.com/froozen/pybot/blob/master/pybot/log.py#L16

**Comment by shak-mar** [comment]
I did a quick test, and it seems you are right. Sorry :D

**Comment by froozen** [comment]
No problem :)
